### ISSUE TITLE
Latest Quests breaks this module due to new custom objective handling

### ISSUE THREAD

**Issue by johnfriedrich** [BerndiVader/MythicMobsQuestsModule#35] opened 2019-04-29 01:22 UTC
This commit seams to break this module:
https://github.com/PikaMug/Quests/commit/666b9bd8bb0801849894fd3474534400422fe51c

Resulting NPE:
https://pastebin.com/RCj1PLgy

https://github.com/BerndiVader/MythicMobsQuestsModule/blob/master/src/main/java/com/gmail/berndivader/mythicmobsquests/MythicMobsKillObjective.java#L67

At least pretty sure this breaks it as downgrading from latst dev to 3.6.5 helped

**Comment by johnfriedrich** [comment] 2019-04-29 18:37
Thanks! Will report later if we have the chance to test it

**Comment by PikaMug** [comment] 2019-05-05 02:26
Clearly I broke something, but I'm a little confused as to what's directly causing this (even looking at BerndiVader's fix). Any insight would be appreciated.

**Comment by PikaMug** [comment] 2019-05-06 23:27
I was just able to produce an identical stack trace with [module dev build 3](http://mc.hackerzlair.org:8080/job/MythicMobsQuests/3/). Using module dev build 4 (containing Berndi's fix) does not produce an error.

Still running blind as to why the change from get() to getOrDefault() was necessary (although it clearly was). If the datamap was returning null values, shouldn't this module's use of Optional.ofNullable suppressed any NPEs? Bear in mind I haven't taken to using Java 8's Optional class myself yet.

**Comment by PikaMug** [comment] 2019-05-06 23:45
Looks like 6bd7f87 isn't a true solution. I was just able to complete a Kill MythicMobs objective with the Internal Name set to "Fairy" by killing a SkeletonKnight mob, so it seems to be defaulting to the "ANY" value (since killing a Fairy also works).

I've also just confirmed that the issue is with Quests, since DungeonsXLQuestsModule exhibited similar behavior in my testing. Hope to pinpoint the issue soon.

**Comment by PikaMug** [comment] 2019-05-07 06:57
Fixed in https://github.com/PikaMug/Quests/commit/2e94a0f63d2e69580b849fb767cd18af72486879

**Comment by johnfriedrich** [comment] 2019-05-07 15:19
What about the last commit in MythicMobsQuestModule? Is it working with that or should we use one version before that?

**Comment by BerndiVader** [comment] 2019-05-11 16:21
Use the current builds of quests and the questsmodule. The issue is fixed. If you can confirm, close please.

**Closed as completed** 2020-02-22 18:50 UTC
